name: Local Link Checker

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  local-link-checker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: run checker
      run: .github/scripts/local-link-checker.sh

    - name: info for fixing
      if: ${{ failure() }}
      run: echo "::error::Broken local links found, please use ./.github/scripts/local-link-checker.sh to check locally"
